#!/bin/bash

echo "🚀 Portfolio Deployment Status"
echo "============================="
echo ""
echo "✅ Code pushed to GitHub"
echo ""
echo "🔧 Next Steps:"
echo ""
echo "1. ADD GITHUB SECRETS:"
echo "   → Go to: https://github.com/yash-waikar/yash-waikar.github.io/settings/secrets/actions"
echo "   → Add these secrets:"
echo "     • REACT_APP_OPENROUTER_API_KEY"
echo "     • REACT_APP_EMAILJS_SERVICE_ID"
echo "     • REACT_APP_EMAILJS_TEMPLATE_CONTACT"
echo "     • REACT_APP_EMAILJS_TEMPLATE_RESUME"
echo "     • REACT_APP_EMAILJS_PUBLIC_KEY"
echo ""
echo "2. ENABLE GITHUB PAGES:"
echo "   → Go to: https://github.com/yash-waikar/yash-waikar.github.io/settings/pages"
echo "   → Set Source to: GitHub Actions"
echo ""
echo "3. CHECK WORKFLOW:"
echo "   → Go to: https://github.com/yash-waikar/yash-waikar.github.io/actions"
echo "   → Watch the deployment progress"
echo ""
echo "📱 Your site will be available at:"
echo "   https://yash-waikar.github.io"
echo ""
echo "💡 Need the API key? Check your .env.local file"
